config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'searches/search'
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get 'home/about',to:'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] # book/:book_id/book_comments
  end

  # resources book_comments, only: [:destory] #/bookcomments/:id

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 検索機能のルーティング
  get '/search', to: 'searches#search'
  # chatのshowアクションをchat/:idとルーティング
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #グループ機能用ルーティング
  resources :groups do
    get "join" => "groups#join"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def new
    @group = Group.new
  end

  def index
    @groups = Group.all
    @book = Book.new
    @user = current_user
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      #owner_idカラムにグループを作成したユーザーのIDを保存
      @group.owner_id = current_user.id
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def join
    # 引数が:group_idなのはroutingが /groups/:group_id/join(.:format) だから
    @group = Group.find(params[:group_id])
    # << は文字列演算子今回の場合、@group.usersという配列の末尾にcurrent_userという要素を破壊的に追加　appendでも可
    @group.users << current_user
    redirect_to groups_path
  end

  def destroy
    @group = Group.find(params[:id])
    # @group.users配列の中からcurrent_userという要素を消去
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_users)
  end

  private

  def group_params
    params.require(:group).permit(:name, :image, :introduction)
  end

  def correct_user
    @group = Group.find(params[:id])
    redirect_to groups_path unless @group.owner_id == current_user.id
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<% if @group.errors.any? %>
  <%= @group.errors.count %>errors prohibited this obj from being saved
  <% @group.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
 <h1>Editing Group</h1>
  <%= form_with model:@group, url: group_path, local:true do |f| %>
  <div class="form-group">
    <p>グループ名</p>
    <%= f.text_field :name, style: "width:100%" %>
  </div>
  <div class="form-group">
    <p>紹介文</p>
    <%= f.text_area :introduction, style: "width:100%" %>
  </div>
  <div class="form-group">
    <label for="inputImage">グループ画像</label>
    <br/>
    <%= f.attachment_field :image %>
  </div>
  <div class="form-group">
    <%= f.submit 'Update Group',class: "btn btn-success" %>
  <% end %>
  </div>
  <span>|</span>
  <%= link_to "Back", groups_path %>
</div>

app/views/groups/index.html.erb
<%= render 'users/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
<h1>Groups</h1>
<%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>グループ名</th>
        <th>紹介文</th>
        <th>メンバー数</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= attachment_image_tag group, :image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:'40x40' %></td>
          <td><%= link_to group.name, group_path(group.id) %></td>
          <td><%= group.introduction %></td>
          <td>　　<%= group.users.count %>人</td>
          <!--グループのオーナーのみeditリンクを表示-->
          <% if group.owner_id == current_user.id %>
          <td><%= link_to "Edit", edit_group_path(group.id), class: "btn btn-sm btn-success"%></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<% if @group.errors.any? %>
  <%= @group.errors.count %>errors prohibited this obj from being saved
  <% @group.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
 <h1>Create Group</h1>
  <%= form_with model:@group, url: groups_path, local:true do |f| %>
  <div class="form-group">
    <p>グループ名</p>
    <%= f.text_field :name, style: "width:100%" %>
  </div>
  <div class="form-group">
    <p>紹介文</p>
    <%= f.text_area :introduction, style: "width:100%" %>
  </div>
  <div class="form-group">
    <label for="inputImage">グループ画像</label>
    <br/>
    <%= f.attachment_field :image %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Group',class: "btn btn-success" %>
  <% end %>
  </div>
  <span>|</span>
  <%= link_to "Back", groups_path %>
</div>

app/views/groups/show.html.erb
<%= render 'users/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
<h1>Group Detail</h1>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>グループ名</th>
        <th>紹介文</th>
        <th>メンバー数</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= link_to attachment_image_tag(@group, :image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:'40x40'),user_path(@group.owner_id) %></td>
          <td><%= link_to @group.name, group_path(@group.id) %></td>
          <td><%= @group.introduction %></td>
          <% @group.users.each do |member| %>
            <td><%= member.name %></td>
          <% end %>
          <!--グループのオーナーのみeditリンクを表示-->
          <% if @group.owner_id == current_user.id %>
            <td><%= link_to "Edit", edit_group_path(@group.id), class: "btn btn-sm btn-success"%></td>
            <td><%#= link_to "Notice an Event", _path(@group.id), class: "btn btn-sm btn-primary"%></td>
            <!--@group.usersの配列の中にcurrent_userが存在する場合-->
          <% elsif @group.users.include?(current_user) %>
            <td><%= link_to "Leave this group", group_path(@group.id), method: :delete, class: "btn btn-sm btn-danger"%></td>
          <% else %>
            <td><%= link_to "Join this group", group_join_path(@group.id), class: "btn btn-sm btn-success"%></td>
          <% end %>
        </tr>
    </tbody>
  </table>
</div>