config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'searches/search'
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get 'home/about',to:'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] # book/:book_id/book_comments
  end

  # resources book_comments, only: [:destory] #/bookcomments/:id

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 検索機能のルーティング
  get '/search', to: 'searches#search'
  # chatのshowアクションをchat/:idとルーティング
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #グループ機能用ルーティング
  resources :groups do
    get "join" => "groups#join"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200}
    has_many :favorites, dependent: :destroy
    # has_many throughは中間テーブルの際に使う記述
    has_many :favorited_users, through: :favorites, source: :user
    has_many :book_comments, dependent: :destroy
    is_impressionable counter_cache: true

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    # 完全一致
    def self.search_for(content, method)
      if method == 'perfect'
        Book.where(title: content)
        # 前方一致　モデル名.where('カラム名 like ?','検索したい文字列%')
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
        # 後方一致
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
        # 部分一致
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :message, presence: true , length: { maximum: 140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name:"Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # チャットルームのアソシエーション
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50}
  #グループのアソシエーション
  has_many :group_users
  has_many :groups, through: :group_users
  # フォローしたときの処理
  def follow(user_id)
  relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  def self.search_for(content, method)
    if method == 'perfect'
       User.where(name: content)
      # 前方一致　モデル名.where('カラム名 like ?','検索したい文字列%')→Userモデルのnameカラムの文字列データのどこかにcontent+(前方一致)と含まれているレコードを取得という意味
    elsif method == 'forward'
      User.where('name LIKE ?', content+'%')
      # 後方一致
    elsif method == 'backward'
      User.where('name LIKE ?', '%'+content)
      # 部分一致
    else
      User.where('name LIKE ?', '%'+content+'%')
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
    # Time.current.at現在の時刻を取得つまり to = 今日の終わり
    to = Time.current.at_end_of_day
    # 6日前のはじめ
    from  = (to - 6.day).at_beginning_of_day
    # sizeでもcountでも表示は問題ないが、反応スピードの関係でsizeを使用
    # ...は範囲演算子例　1..5 は1～5 1...5は終端を含まないので1～4の意味
    # Book.allと書かない理由はincludes(引数)と記述した方が余分なsqlを発行しなくなるため軽くなる
    # Arrayオブジェクト.sort {|a, b| ... } Arrayは配列の意味　配列の中身をa bを用いてどのように比較するか可能
    @books = Book.includes(:favorited_users).
      sort {|a,b|
      # a <=> b基本的な比較演算子　 a < b であれば -1、a == b であれば 0、a > b であれば 1、比較できない時は nil を返えす。
      # bを先に記述して降順にしている。
    b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
    a.favorited_users.includes(:favorites).where(created_at: from...to).size}
      
    @book = Book.new
    # @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').pluck(:book_id))
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new  = Book.new
    @book_comment= BookComment.new
    #bookの詳細ページにアクセスするとPV数が1増える。impressionistはgemをいれることで使えるメソッド
    impressionist(@book, nil, unique: [:ip_address])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
  # noticeとalertがキーの場合下記のように省略できます。
      redirect_to book_path(@book.id), notice:"You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/devise_helper.rb
# deviseのflash keyにはデフォルトでniticeやalertが使われている。これを他のkeyに置き換える記述です。
module DeviseHelper
  # def bootstrap_alert(key)
  #   case key
  #   when "alert"
  #     "warning"
  #   when "notice"
  #     "success"
  #   when "error"
  #     "danger"
  #   end
  # end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 63, 63, format: 'jpeg', fallback: "no_image.jpg",size:'63x63' %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
      <tr>
        <th>follows:</th>
        <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
      </tr>
      <tr>
        <th>followers:</th>
        <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
      </tr>
    </tbody>
  </table>

    <%= link_to "", edit_user_path(current_user), class: "fas fa-user-cog btn btn-outline-secondary btn-block" %>



  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <p>Title</p>
    <%= f.text_field :title,style: "width:100%" %>
  </div>
  <div class="form-group">
    <p>Opinion</p>
    <%= f.text_area :body,style: "width:100%" %>
  </div>
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <h2>Users info</h2>
  <%= form_with model:@user, local:true do |f| %>
  <div class="form-group">
    <label for="inputName">Name</label>
    <br/>
    <%= f.text_field :name, id:"inputName", placeholder:"名前",style: "width:100%" %>
  </div>
  <div class="form-group">
    <label for="inputImage">Image</label>
    <br/>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  </div>
  <div class="form-group">
    <label for="inputIntroduction">Introduction</label>
    <br/>
    <%= f.text_area :introduction, style: "width:100%" %>
  </div>
    <br/>
    <%= f.submit "Update User",class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'users/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
<h1>Users</h1>
<%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:'40x40' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td>
            <% if user != current_user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'books/showlist', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to attachment_image_tag(@user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:'40x40'),user_path(@user.id) %></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
          <td></td>
          <td></td>
        </tr>

      <% end %>
    </tbody>
  </table>
</div>