config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'searches/search'
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get 'home/about',to:'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] # book/:book_id/book_comments
  end

  # resources book_comments, only: [:destory] #/bookcomments/:id

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 検索機能のルーティング
  get '/search', to: 'searches#search'
  # chatのshowアクションをchat/:idとルーティング
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #グループ機能用ルーティング
  resources :groups do
    get "join" => "groups#join"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200}
    has_many :favorites, dependent: :destroy
    # has_many throughは中間テーブルの際に使う記述
    has_many :favorited_users, through: :favorites, source: :user
    has_many :book_comments, dependent: :destroy
    is_impressionable counter_cache: true

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    # 完全一致
    def self.search_for(content, method)
      if method == 'perfect'
        Book.where(title: content)
        # 前方一致　モデル名.where('カラム名 like ?','検索したい文字列%')
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
        # 後方一致
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
        # 部分一致
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
    # Time.current.at現在の時刻を取得つまり to = 今日の終わり
    to = Time.current.at_end_of_day
    # 6日前のはじめ
    from  = (to - 6.day).at_beginning_of_day
    # sizeでもcountでも表示は問題ないが、反応スピードの関係でsizeを使用
    # ...は範囲演算子例　1..5 は1～5 1...5は終端を含まないので1～4の意味
    # Book.allと書かない理由はincludes(引数)と記述した方が余分なsqlを発行しなくなるため軽くなる
    # Arrayオブジェクト.sort {|a, b| ... } Arrayは配列の意味　配列の中身をa bを用いてどのように比較するか可能
    @books = Book.includes(:favorited_users).
      sort {|a,b|
      # a <=> b基本的な比較演算子　 a < b であれば -1、a == b であれば 0、a > b であれば 1、比較できない時は nil を返えす。
      # bを先に記述して降順にしている。
    b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
    a.favorited_users.includes(:favorites).where(created_at: from...to).size}
      
    @book = Book.new
    # @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').pluck(:book_id))
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new  = Book.new
    @book_comment= BookComment.new
    #bookの詳細ページにアクセスするとPV数が1増える。impressionistはgemをいれることで使えるメソッド
    impressionist(@book, nil, unique: [:ip_address])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
  # noticeとalertがキーの場合下記のように省略できます。
      redirect_to book_path(@book.id), notice:"You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_showlist.html.erb
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 63, 63, format: 'jpeg', fallback: "no_image.jpg",size:'63x63' %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>
              <th>follows:</th>
              <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
            </tr>
            <tr>
              <th>followers:</th>
              <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
            </tr>
            <tr>
              <th>
              <% if @user != current_user %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-info" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-success" %>
                <% end %>
              <% end %>
              </th>
            </tr>
            <tr>
              <th>
                <% if current_user != @user %>
                  <%= link_to 'Chatを始めよう', chat_path(@user.id) %>
                <% end %> 
              </th>
            </tr>
          </tbody>
        </table>

          <%= link_to "", edit_user_path(user), class: "fas fa-user-cog btn btn-outline-secondary btn-block" %>


      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
      <div class="form-group">
        <p>Title</p>
        <%= f.text_field :title,style: "width:100%" %>
      </div>
      <div class="form-group">
        <p>Opinion</p>
        <%= f.text_area :body,style: "width:100%" %>
      </div>
        <%= f.submit 'Create Book', class: "btn btn-success " %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
 <h1>Editing Book</h1>
  <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <div class="form-group">
    <p>Title</p>
    <%= f.text_field :title, style: "width:100%" %>
  </div>
  <div class="form-group">
    <p>Opinion</p>
    <%= f.text_area :body, style: "width:100%" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Update Book',class: "btn btn-success" %>
  <% end %>
  </div>
  <%= link_to "Show", book_path %>
  <span>|</span>
  <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
<%= render 'users/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<h1>Books</h1>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40'),user_path(book.user.id) %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td id="favorite_buttons_<%= book.id %>">
            <%= render 'favorites/favorite-btn', book: book %>
          </td>
          <td>
            <%= link_to " コメント数 : #{book.book_comments.count}", book_path(book.id) %>
          </td>
          <td>閲覧数: <%= book.impressions_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<%= render 'books/showlist', book: @book_new, user: @user %>
<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
      <td><%= link_to attachment_image_tag(@user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:'40x40'),user_path(@user.id) %><br/><%= link_to @user.name,user_path(@user.id) %></td>
      <td><%= link_to @book.title, book_path %></td>
      <td><%= @book.body %></td>
      <% if @user == current_user %>
        <td><%= link_to "Edit", edit_book_path, class: "btn btn-sm btn-success"%></td>
        <td><%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
      <% else %>
        <td>
          <% if @book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                ♥<%= @book.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(@book), method: :post do %>
                ♡<%= @book.favorites.count %>
              <% end %>
            </p>
          <% end %>
        </td>
        <td><p>コメント数：<%= @book.book_comments.count %></p></td>
        <td>閲覧数: <%= @book.impressions_count %></td>
      <% end %>
      </tr>
    </tbody>
  </table>
       <div class="bookcomment">
           <%= render 'book_comments/bookcomment', book: @book, book_comment: @book_comment %>
       </div>
</div>