config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'searches/search'
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get 'home/about',to:'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] # book/:book_id/book_comments
  end

  # resources book_comments, only: [:destory] #/bookcomments/:id

  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # 検索機能のルーティング
  get '/search', to: 'searches#search'
  # chatのshowアクションをchat/:idとルーティング
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  #グループ機能用ルーティング
  resources :groups do
    get "join" => "groups#join"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200}
    has_many :favorites, dependent: :destroy
    # has_many throughは中間テーブルの際に使う記述
    has_many :favorited_users, through: :favorites, source: :user
    has_many :book_comments, dependent: :destroy
    is_impressionable counter_cache: true

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    # 完全一致
    def self.search_for(content, method)
      if method == 'perfect'
        Book.where(title: content)
        # 前方一致　モデル名.where('カラム名 like ?','検索したい文字列%')
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
        # 後方一致
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
        # 部分一致
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :message, presence: true , length: { maximum: 140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name:"Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # チャットルームのアソシエーション
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50}
  #グループのアソシエーション
  has_many :group_users
  has_many :groups, through: :group_users
  # フォローしたときの処理
  def follow(user_id)
  relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  def self.search_for(content, method)
    if method == 'perfect'
       User.where(name: content)
      # 前方一致　モデル名.where('カラム名 like ?','検索したい文字列%')→Userモデルのnameカラムの文字列データのどこかにcontent+(前方一致)と含まれているレコードを取得という意味
    elsif method == 'forward'
      User.where('name LIKE ?', content+'%')
      # 後方一致
    elsif method == 'backward'
      User.where('name LIKE ?', '%'+content)
      # 部分一致
    else
      User.where('name LIKE ?', '%'+content+'%')
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/devise_helper.rb
# deviseのflash keyにはデフォルトでniticeやalertが使われている。これを他のkeyに置き換える記述です。
module DeviseHelper
  # def bootstrap_alert(key)
  #   case key
  #   when "alert"
  #     "warning"
  #   when "notice"
  #     "success"
  #   when "error"
  #     "danger"
  #   end
  # end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notification.html.erb
<!--deviseのflashメッセージを表示するため。-->
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
 <% end %>
</div>
<!--app/hlepers/devise_helper.rbを作成済で以下記述でdeviseのflashを修飾-->
 <!--flash.each do |key, value| %>-->
  <!--<div class="alert alert-<%# bootstrap_alert(key) %>">-->
    <!--<strong>-->
      <%# value %>
    <!--</strong>-->
  <!--</div>-->
 <!--end % >-->

app/views/layouts/_search.html.erb
<div class="row">
  <div class="search_form mx-auto mt-3">
    <%= form_with url: search_path, method: :get, local:true do |f| %>
    <%= f.text_field :content %>
    <!--f.select~でプルダウン作成-->
    <%= f.select :model,options_for_select({"User"=>"user","Book"=>"book"}) %>
    <%= f.select :method,options_for_select({"完全一致"=>"perfect","前方一致"=>"forward","後方一致"=>"backward","部分一致"=>"partial"}) %>
    <%= f.submit'検索' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/0bc84af185.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Home", user_path(current_user.id), class: "nav-link text-light fas fa-home" %>
              </li>
              <li class="nav-item">
                <%= link_to "Users", users_path, class: "nav-link text-light fas fa-users" %>
              </li>
              <li class="nav-item">
                <%= link_to "Books", books_path, class: "nav-link text-light fas fa-book-open" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link text-light fas fa-sign-out-alt" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link text-light fas fa-home" %>
              </li>
              <li class="nav-item">
                <%= link_to "About", home_about_path, class: "nav-link text-light fas fa-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-light fas fa-user-plus" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, class: "nav-link text-light fas fa-sign-in-alt" %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <!--検索フォームの部分テンプレート挿入-->
      <% if user_signed_in? %>
          <%= render 'layouts/search' %>
      <% end %>
    </header>
    <main>
      <%= render 'layouts/notification' %>

      <div class="container px-5 px-sm-0 mt-3">
       <div class="row">

    <%= yield %>
        </div>
      </div>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>